environment:
  # See README for information on the token
  BINSTAR_TOKEN:
    secure: FU5GdoruzB7YIvgFGqewEPvLiKhu8nY9m92egLN6lAFeIj+dlkKm5zBeRzmAM35G

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

    - PYTHON: "C:\\Miniconda37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "37"

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

init:
    - ECHO %SYS_PYTHON% %SYS_PYTHON_VERSION% %SYS_PYTHON_ARCH% %HOME%

install:

  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  - set "CONDA_ROOT=C:\Miniconda%CONDA_PY%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --set auto_update_conda no
  - conda info
  - python -c "import sys; print(sys.version)"
  - python -c "import sys; print(sys.executable)"
  - python -c "import sys; print(sys.prefix)"
  - conda update -q --all
  - conda install -q pip conda-build jinja2 anaconda-client
  - conda install -yq conda-build=3.15.1
  - set PATH
  - conda build --version

build: false

test_script:
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - set PATH
  - echo "safety_checks: disabled" >> ~/.condarc
  - echo "local_repodata_ttl: 1800" >> ~/.condarc
  - conda install -y conda-verify
  - conda build conda-recipe --quiet
  # Move the conda package into the current directory, to register it
  # as an "artifact" for Appveyor. cmd.exe does't have good globbing, so
  # we'll use a simple python script.
  - python continuous-integration\move-conda-package.py conda-recipe

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'

on_success:
  # Upload built binaries to binstar.org. The globbing and handling of the
  # exit-status code is tricky in cmd.exe or powershell, so we're just using
  # a python script.
  - python continuous-integration\binstar-push.py
