package:
  name: b4msa
  version: "1.2.6"

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - nltk

  run:
    - python
    - scikit-learn
    - nltk

test:
  requires:
    - nose
    - numpy
    - scipy
    - scikit-learn
    - nltk
    - coverage

  imports:
    - b4msa

  commands:
    - nosetests --verbose -exe b4msa
    - b4msa-params --help
    - b4msa-train --help
    - b4msa-test --help

about:
  home: https://github.com/ingeotec/b4msa
  summary: "Baselines for Multilingual Sentiment Analysis."
  license: Apache

